### PR TITLE
Name taken

### PR DESCRIPTION
**Pull request by craigaaroncampbell**
add res.data.nameTaken: true to res object on signup route if name is already taken

### CODE REVIEW

**Comment by toastynerd** [comment]
Interesting, looks like this is failing travis.

**Comment by toastynerd** [comment]
You should update the tests to go with this change

**Comment by craigaaroncampbell** [comment]
added the test. they are still all passing on my local machine. Don't know why Travis is having a problem...

**Comment by toastynerd** [comment]
lgtm

**Pull request merged**
